version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    overwrite: yes
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStop:
    - location: deployscript/ApplicationStop.sh
      timeout: 120
      runas: root
  BeforeInstall:
    - location: deployscript/BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deployscript/AfterInstall.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: deployscript/ApplicationStart.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: deployscript/ValidateService.sh
      timeout: 60
      runas: ubuntu