version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    overwrite: yes
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: deployscript/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deployscript/post_install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: deployscript/run.sh
      timeout: 120
      runas: ubuntu
  ApplicationStop:
    - location: deployscript/stopcmmd.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: deployscript/validate.sh
      timeout: 60
      runas: ubuntu
