version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
        - echo "getting package for phalcon"
        - sudo apt-get install curl -y
        - sudo php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - php composer-setup.php --file-name=composer
  pre_build:
    commands:
        - echo "start building" 
        - echo "test composer"
        - php composer.phar --version
  build:
    commands:
        - sudo php composer.phar install
  post_build:
    commands:
        - echo Build vendor completed on `date`
      # - command
artifacts:
  files:
    - '**/*'
    # - location
  name: cicd-phalcon-project
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths

