version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
        - echo "getting package for phalcon"
        - sudo apt-get install composer -y
  pre_build:
    commands:
        - echo "start building" 
        - echo "test composer"
        - comm=$(composer --version)
        - echo "$comm"
  build:
    commands:
        - commm=$(composer install)
        - echo "$commm"
  post_build:
    commands:
        - echo Build vendor completed on `date`
      # - command
artifacts:
  files:
    - '**/*'
    # - location
  name: cicd-phalcon-project
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths

